---
include:
  - docker-socket-proxy/compose.yaml
  - nginx/compose.yaml
  - stepca/compose.yaml
  - homepage/compose.yaml
  - it-tools/compose.yaml
  - firefox/compose.yaml
  - obsidian/compose.yaml
  - webtop/compose.yaml
  - traefik/compose.yaml

networks:
  default:
    external: true
    name: mac-pro-composes  # shared network
